version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: 'redis:latest'
    ports:
      - "6380:6379"
  consul:
    image: 'consul:1.15.4'
    ports:
      - "8501:8500"
    command: "consul agent -dev -client=0.0.0.0"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
