// Code generated by hertz generator.

package cart

import (
	cart "TikTokMall/biz/model/cart"
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// AddItem .
// @router /cart/add [POST]
func AddItem(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.AddItemReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cart.AddItemResp)

	c.JSON(consts.StatusOK, resp)
}

// GetCart .
// @router /cart/{user_id} [GET]
func GetCart(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.GetCartReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cart.GetCartResp)

	c.JSON(consts.StatusOK, resp)
}

// EmptyCart .
// @router /cart/{user_id} [DELETE]
func EmptyCart(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.EmptyCartReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cart.EmptyCartResp)

	c.JSON(consts.StatusOK, resp)
}
