apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: tiktok-mall
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: tiktok-mall/cart:latest
        ports:
        - containerPort: 8080
        env:
        - name: GO_ENV
          value: "prod"
        volumeMounts:
        - name: config
          mountPath: /app/conf
        - name: logs
          mountPath: /var/log/cart
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: cart-config
      - name: logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: tiktok-mall
spec:
  selector:
    app: cart
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 