// Code generated by hertz generator.

package auth

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delivertokenbyrpcMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verifytokenbyrpcMw() []app.HandlerFunc {
	// your code...
	return nil
}
