// Code generated by Kitex v0.9.1. DO NOT EDIT.

package paymentservice

import (
	payment "TikTokMall/app/payment/kitex_gen/payment"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Charge(ctx context.Context, Req *payment.ChargeReq, callOptions ...callopt.Option) (r *payment.ChargeResp, err error)
	Refund(ctx context.Context, Req *payment.RefundReq, callOptions ...callopt.Option) (r *payment.RefundResp, err error)
	AlipayCharge(ctx context.Context, Req *payment.AlipayChargeReq, callOptions ...callopt.Option) (r *payment.AlipayChargeResp, err error)
	AlipayRefund(ctx context.Context, Req *payment.AlipayRefundReq, callOptions ...callopt.Option) (r *payment.AlipayRefundResp, err error)
	AlipayNotify(ctx context.Context, Req *payment.AlipayNotifyReq, callOptions ...callopt.Option) (r *payment.AlipayNotifyResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPaymentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPaymentServiceClient struct {
	*kClient
}

func (p *kPaymentServiceClient) Charge(ctx context.Context, Req *payment.ChargeReq, callOptions ...callopt.Option) (r *payment.ChargeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Charge(ctx, Req)
}

func (p *kPaymentServiceClient) Refund(ctx context.Context, Req *payment.RefundReq, callOptions ...callopt.Option) (r *payment.RefundResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Refund(ctx, Req)
}

func (p *kPaymentServiceClient) AlipayCharge(ctx context.Context, Req *payment.AlipayChargeReq, callOptions ...callopt.Option) (r *payment.AlipayChargeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AlipayCharge(ctx, Req)
}

func (p *kPaymentServiceClient) AlipayRefund(ctx context.Context, Req *payment.AlipayRefundReq, callOptions ...callopt.Option) (r *payment.AlipayRefundResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AlipayRefund(ctx, Req)
}

func (p *kPaymentServiceClient) AlipayNotify(ctx context.Context, Req *payment.AlipayNotifyReq, callOptions ...callopt.Option) (r *payment.AlipayNotifyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AlipayNotify(ctx, Req)
}
