// Code generated by hertz generator.

package order

import (
	"context"

	order "TikTokMall/biz/model/order"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PlaceOrder .
// @router /order/place [POST]
func PlaceOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.PlaceOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(order.PlaceOrderResp)

	c.JSON(consts.StatusOK, resp)
}

// ListOrder .
// @router /order/list/{user_id} [GET]
func ListOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.ListOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(order.ListOrderResp)

	c.JSON(consts.StatusOK, resp)
}

// MarkOrderPaid .
// @router /order/mark_paid [PUT]
func MarkOrderPaid(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.MarkOrderPaidReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(order.MarkOrderPaidResp)

	c.JSON(consts.StatusOK, resp)
}
