// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	auth "TikTokMall/biz/router/auth"
	cart "TikTokMall/biz/router/cart"
	checkout "TikTokMall/biz/router/checkout"
	order "TikTokMall/biz/router/order"
	payment "TikTokMall/biz/router/payment"
	product "TikTokMall/biz/router/product"
	user "TikTokMall/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user.Register(r)

	product.Register(r)

	payment.Register(r)

	order.Register(r)

	checkout.Register(r)

	cart.Register(r)

	auth.Register(r)
}
